---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arb-configuration
data:
  queueSize: "30"
  batchSize: "10"
  requestTimeout: "500ms"
  retries: "5"
  services: |-
    https://arblogger1/200
    https://arblogger2/404
    http://arblogger3/503
---
apiVersion: v1
kind: Service
metadata:
  name: arb
spec:
  ports:
  - name: grpc
    port: 9001
    targetPort: 9001
  selector:
    app.kubernetes.io/name: arb 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: arb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arb
    spec:
      containers:
      - image: ko://github.com/datawire/arb
        name: arb
        env:
        - name: "ARB_INSECURE_TLS"
          value: "true"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config-volume
          mountPath: /etc/arb-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: arb-configuration
